site_name: Hyperion

markdown_extensions:
  - admonition

# Repository
repo_name: 'felipeasf/hyperion-docs'
repo_url: 'https://github.com/felipeasf/hyperion-docs'

nav:
    - Home: index.md
    - Getting Started: install.md
    - Docker: docker.md
    - Data Structure: data.md
    - Roadmap: roadmap.md

#theme: readthedocs
theme:
  name: 'material'
  palette:
    primary: 'Blue Grey'
    accent: 'Blue Grey'
  logo:
    icon: 'history'