site_name: Hyperion

markdown_extensions:
  - admonition

# Repository
repo_name: 'felipeasf/hyperion-docs'
repo_url: 'https://github.com/felipeasf/hyperion-docs'

nav:
    - Home: index.md
    - Providers:
      - Quick Start: quickstart.md
      - Install: install.md
      - Docker: docker.md
      - Connections: connections.md
      - Chain Configuration: chain.md
      - Ecosystem: ecosystem.md
    - Users / Developers:
      - Getting Started: howtouse.md
      - Stream Client: stream_client.md
      - Endpoint List: endpoint.md
    - API Reference: api.md
    - Troubleshooting:
      - Kibana: kibana.md
      - RabbitMQ: rabbit.md
      - FAQ: faq.md

#theme: readthedocs
theme:
  name: 'material'
  palette:
    primary: 'Blue Grey'
    accent: 'Blue Grey'
  logo:
    icon: 'history'
